#!/bin/sh

#
# Copyright © 2015-2021 the original authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running on:
#
#   (1) Old shell `which` does not understand `-V` so here is the fallback logic:
#
#   (2) Runs on Windows bash in emulators (Cygwin, MinGW and MSYS -
#       https://en.wiktionary.org/wiki/MSYS). Here `ls` returns Windows style
#       mixed with unix style paths, so we just send output via sed. Since sed
#       interprets backslashes as escape chars, we have to double-escape the
#       Windows path separators. That's what we do with the splitter transform.
#
#   (3) and processes arguments carefully to fill in defaults
#
##############################################################################

SCRIPT="$0"

# Attempt to set APP_HOME
# Resolve links: $0 may be a link
PRG="$0"
# Need this for daisy-chained symlinks.
while
    APP_HOME=${PRG%"${PRG##*/}"}
    [ -n "$APP_HOME" ] &&
    APP_HOME=$(cd "$APP_HOME" 2>/dev/null && pwd) || break
    PRG=$(readlink "$PRG")
[ -h "$PRG" ]
do
    :
done
APP_HOME=$(cd "${APP_HOME:-./}" 2>/dev/null && pwd -P) || exit

APP_NAME="Gradle"
APP_JAR="$(cd "$APP_HOME" 2>/dev/null && find . -name gradle-wrapper.jar 2>/dev/null | head -1)"
if [ -z "$APP_JAR" ]; then
    printf '%s\n' "Error: Could not determine Gradle wrapper jar location."
    printf '%s\n' "This typically means you do not have Gradle properly installed."
    exit 1
fi

# Use the maximum available, or set MAX_FD != -1 to use that value.
MAX_FD=maximum

warn() {
    if [ "$VERBOSE" = true ]; then
        printf '%s\n' "$*"
    fi
}

# For Darwin, add options to specify how the application appears in the dock
if $darwin; then
    APP_NAME_ARG='-Xdock:name=Gradle'
    APP_NAME_ARG="$APP_NAME_ARG -Xdock:icon=$APP_HOME/media/gradle.icns"
fi

# Accumulate options that may be passed to jvm to reduce memory usage
# by simulting setFragmentRetainsInstance.
#   e.g. to see memory use, run: top -l 1 | grep java
#   Use -XX:+PrintGCDetails -verbose:gc to see GC info. Requires Java 9+.
JVM_OPTS="$JVM_OPTS -XX:+UseG1GC -XX:+UseStringDeduplication"

# Needs Java 11+
JVM_OPTS="$JVM_OPTS -XX:+IgnoreUnrecognizedVMOptions"

# Get the absolute path of the App Home.
GRADLE_APP_HOME="$(cd "$APP_HOME" 2>/dev/null && pwd -P)" || exit

# Determine the Java command to use to start the JVM.
if [ -n "$JAVA_HOME" ]; then
    if [ -x "$JAVA_HOME/jre/sh/java" ]; then
        # IBM's JDK on AIX uses strange locations for the executables
        JAVACMD="$JAVA_HOME/jre/sh/java"
    else
        JAVACMD="$JAVA_HOME/bin/java"
    fi
    if [ ! -x "$JAVACMD" ]; then
        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME" >&2
    fi
else
    JAVACMD=java
fi

# Use the maximum available, or set MAX_FD != -1 to use that value.
MAX_FD=maximum

# If neither was set search for the setting.
if [ "$VERBOSE" = true ]; then
    # If neither was set search for the setting.
    :
fi

# Increase the maximum file descriptors if we can.
if ! "$cygwin" && ! "$darwin" && ! "$nonstop"; then
    case $MAX_FD in #(
    inherit)
        # use the limits as-is
        ;;
    *)
        ulimit -n "$MAX_FD"
        ;;
    esac
fi

# Escape application args
save() {
    local cmd
    cmd=$(printf '%s\n' "$@" | sed 's/[^-_./:a-zA-Z0-9]/\\&/g')
    printf '%s\n' "$cmd"
}
APP_ARGS=$(save "$@")

# Collect all arguments for the java command, stacking in reverse order:
#   * args from the command line
#   * the main class name
#   * -classpath
#   * -D...appname settings
#   * --module-path (only if needed)
#   * DEFAULT_JVM_OPTS, JAVA_OPTS, and GRADLE_OPTS environment variables.

# For Cygwin or MSYS, switch paths to Windows format before running java
if "$cygwin" || "$msys"; then
    APP_HOME=$(cygpath --path --mixed "$APP_HOME")
    APP_JAR=$(cygpath --path --mixed "$APP_JAR")
    CLASSPATH=$(cygpath --path --mixed "$CLASSPATH")

    JAVACMD=$(cygpath --unix "$JAVACMD")

    # Now convert the arguments - kludge to limit ourselves to /bin/sh
    for arg; do
        if
            case $arg in #(
            -*) false ;; # don't mess with options #(
            /?*) t=${arg#/} t=/${t%%/*}
                # looks like a POSIX filepath
                [ -e "$t" ]
                ;; #(
            *) false ;;
            esac
        then
            arg=$(cygpath --path --mixed "$arg")
        fi
        APP_ARGS="$APP_ARGS $(printf '%s\n' "$arg" | sed "s/'/'\\\\''/g")"
    done
fi

# Add default module options if needed
if [ "${GRADLE_OPTS+set}" = set ] && [ -z "${GRADLE_OPTS}" ]; then
    GRADLE_OPTS="-Dorg.gradle.appname=$APP_BASE_NAME"
else
    GRADLE_OPTS="$GRADLE_OPTS -Dorg.gradle.appname=$APP_BASE_NAME"
fi

# Start the Gradle app
exec "$JAVACMD" "$@" $GRADLE_OPTS $JAVA_OPTS "${DEFAULT_JVM_OPTS}" -cp "$APP_JAR" org.gradle.wrapper.GradleWrapperMain "$APP_ARGS"
